//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEWEEntity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201105061557\\SQLEXPRESS;Initial Catalog=EMEWEQC;Persist Security I" +
            "nfo=True;User ID=sa")]
        public string EMEWEQCConnectionString1 {
            get {
                return ((string)(this["EMEWEQCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201105061557\\SQLEXPRESS;Initial Catalog=EMEWEQC;Persist Security I" +
            "nfo=True;User ID=sa;Password=sa")]
        public string EMEWEQCConnectionString {
            get {
                return ((string)(this["EMEWEQCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XP-201104021208\\SQL2008;Initial Catalog=EMEWEQC;Persist Security Info" +
            "=True;User ID=sa")]
        public string EMEWEQCConnectionString2 {
            get {
                return ((string)(this["EMEWEQCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWEQC;User ID=sa")]
        public string EMEWEQCConnectionString3 {
            get {
                return ((string)(this["EMEWEQCConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE-150\\MSSQL2008;Initial Catalog=EMEWEQC;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string EMEWEQCConnectionString4 {
            get {
                return ((string)(this["EMEWEQCConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RRJFZS3MEZLAVV8;Initial Catalog=EMEWEQC;User ID=sa")]
        public string EMEWEQCConnectionString5 {
            get {
                return ((string)(this["EMEWEQCConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RRJFZS3MEZLAVV8;Initial Catalog=EMEWEQC;Persist Security Info=True;Us" +
            "er ID=sa")]
        public string EMEWEQCConnectionString6 {
            get {
                return ((string)(this["EMEWEQCConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JSDD01;Initial Catalog=EMEWEQC;Persist Security Info=True;User ID=sa")]
        public string EMEWEQCConnectionString7 {
            get {
                return ((string)(this["EMEWEQCConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EMEWEQC;User ID=sa")]
        public string EMEWEQCConnectionString8 {
            get {
                return ((string)(this["EMEWEQCConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CQEMEWEQC;Persist Security Info=True;User ID=sa")]
        public string CQEMEWEQCConnectionString {
            get {
                return ((string)(this["CQEMEWEQCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CQEMEWEQC;User ID=sa;Password=sa")]
        public string CQEMEWEQCConnectionString1 {
            get {
                return ((string)(this["CQEMEWEQCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=JSEMEWEQC;User ID=sa;Password=sa")]
        public string JSEMEWEQCConnectionString {
            get {
                return ((string)(this["JSEMEWEQCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CQEMEWEQC;Persist Security Info=True;User ID=sa;Pas" +
            "sword=sa")]
        public string CQEMEWEQCConnectionString2 {
            get {
                return ((string)(this["CQEMEWEQCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.130;Initial Catalog=CQEMEWEQC;Persist Security Info=True;Us" +
            "er ID=sa;Password=sa")]
        public string CQEMEWEQCConnectionString3 {
            get {
                return ((string)(this["CQEMEWEQCConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EMEWE006-PC\\EMEWE;Initial Catalog=JXEMEWEQC;User ID=sa;Password=12345" +
            "6")]
        public string JXEMEWEQCConnectionString {
            get {
                return ((string)(this["JXEMEWEQCConnectionString"]));
            }
        }
    }
}
