#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEWEEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CQEMEWEQC")]
	public partial class NewDataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUserInfo2(UserInfo2 instance);
    partial void UpdateUserInfo2(UserInfo2 instance);
    partial void DeleteUserInfo2(UserInfo2 instance);
    #endregion
		
		public NewDataClasses1DataContext() : 
				base(global::EMEWEEntity.Properties.Settings.Default.CQEMEWEQCConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public NewDataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewDataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserInfo2> UserInfo2
		{
			get
			{
				return this.GetTable<UserInfo2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserInfo2")]
	public partial class UserInfo2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _UserName;
		
		private string _UserPhone;
		
		private string _UserAddress;
		
		private string _UserPermission;
		
		private string _UserIdentification;
		
		private string _UserCarId;
		
		private System.Nullable<System.DateTime> _UserCreateTime;
		
		private string _UserCreateName;
		
		private System.Nullable<int> _User_Duty_ID;
		
		private System.Nullable<int> _User_Dictionary_ID;
		
		private string _UserRemark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnUserPhoneChanging(string value);
    partial void OnUserPhoneChanged();
    partial void OnUserAddressChanging(string value);
    partial void OnUserAddressChanged();
    partial void OnUserPermissionChanging(string value);
    partial void OnUserPermissionChanged();
    partial void OnUserIdentificationChanging(string value);
    partial void OnUserIdentificationChanged();
    partial void OnUserCarIdChanging(string value);
    partial void OnUserCarIdChanged();
    partial void OnUserCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUserCreateTimeChanged();
    partial void OnUserCreateNameChanging(string value);
    partial void OnUserCreateNameChanged();
    partial void OnUser_Duty_IDChanging(System.Nullable<int> value);
    partial void OnUser_Duty_IDChanged();
    partial void OnUser_Dictionary_IDChanging(System.Nullable<int> value);
    partial void OnUser_Dictionary_IDChanged();
    partial void OnUserRemarkChanging(string value);
    partial void OnUserRemarkChanged();
    #endregion
		
		public UserInfo2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPhone", DbType="VarChar(100)")]
		public string UserPhone
		{
			get
			{
				return this._UserPhone;
			}
			set
			{
				if ((this._UserPhone != value))
				{
					this.OnUserPhoneChanging(value);
					this.SendPropertyChanging();
					this._UserPhone = value;
					this.SendPropertyChanged("UserPhone");
					this.OnUserPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAddress", DbType="VarChar(300)")]
		public string UserAddress
		{
			get
			{
				return this._UserAddress;
			}
			set
			{
				if ((this._UserAddress != value))
				{
					this.OnUserAddressChanging(value);
					this.SendPropertyChanging();
					this._UserAddress = value;
					this.SendPropertyChanged("UserAddress");
					this.OnUserAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPermission", DbType="VarChar(1000)")]
		public string UserPermission
		{
			get
			{
				return this._UserPermission;
			}
			set
			{
				if ((this._UserPermission != value))
				{
					this.OnUserPermissionChanging(value);
					this.SendPropertyChanging();
					this._UserPermission = value;
					this.SendPropertyChanged("UserPermission");
					this.OnUserPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIdentification", DbType="VarChar(100)")]
		public string UserIdentification
		{
			get
			{
				return this._UserIdentification;
			}
			set
			{
				if ((this._UserIdentification != value))
				{
					this.OnUserIdentificationChanging(value);
					this.SendPropertyChanging();
					this._UserIdentification = value;
					this.SendPropertyChanged("UserIdentification");
					this.OnUserIdentificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCarId", DbType="VarChar(100)")]
		public string UserCarId
		{
			get
			{
				return this._UserCarId;
			}
			set
			{
				if ((this._UserCarId != value))
				{
					this.OnUserCarIdChanging(value);
					this.SendPropertyChanging();
					this._UserCarId = value;
					this.SendPropertyChanged("UserCarId");
					this.OnUserCarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UserCreateTime
		{
			get
			{
				return this._UserCreateTime;
			}
			set
			{
				if ((this._UserCreateTime != value))
				{
					this.OnUserCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._UserCreateTime = value;
					this.SendPropertyChanged("UserCreateTime");
					this.OnUserCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreateName", DbType="VarChar(100)")]
		public string UserCreateName
		{
			get
			{
				return this._UserCreateName;
			}
			set
			{
				if ((this._UserCreateName != value))
				{
					this.OnUserCreateNameChanging(value);
					this.SendPropertyChanging();
					this._UserCreateName = value;
					this.SendPropertyChanged("UserCreateName");
					this.OnUserCreateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Duty_ID", DbType="Int")]
		public System.Nullable<int> User_Duty_ID
		{
			get
			{
				return this._User_Duty_ID;
			}
			set
			{
				if ((this._User_Duty_ID != value))
				{
					this.OnUser_Duty_IDChanging(value);
					this.SendPropertyChanging();
					this._User_Duty_ID = value;
					this.SendPropertyChanged("User_Duty_ID");
					this.OnUser_Duty_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Dictionary_ID", DbType="Int")]
		public System.Nullable<int> User_Dictionary_ID
		{
			get
			{
				return this._User_Dictionary_ID;
			}
			set
			{
				if ((this._User_Dictionary_ID != value))
				{
					this.OnUser_Dictionary_IDChanging(value);
					this.SendPropertyChanging();
					this._User_Dictionary_ID = value;
					this.SendPropertyChanged("User_Dictionary_ID");
					this.OnUser_Dictionary_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRemark", DbType="VarChar(1000)")]
		public string UserRemark
		{
			get
			{
				return this._UserRemark;
			}
			set
			{
				if ((this._UserRemark != value))
				{
					this.OnUserRemarkChanging(value);
					this.SendPropertyChanging();
					this._UserRemark = value;
					this.SendPropertyChanged("UserRemark");
					this.OnUserRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
